import mongoose from 'mongoose'

export const PAYMENT_RESULTS = ['pending', 'success', 'failed']

/**
 * A payment attempt against a booking.
 *
 * This project uses a demo payment flow — there is no real gateway
 * integrated. The `provider` field records that honestly, so nobody
 * later mistakes these rows for real settled transactions.
 */
export const PAYMENT_PROVIDERS = ['demo']

const paymentSchema = new mongoose.Schema(
  {
    booking: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Booking',
      required: true,
      index: true,
    },

    tenant: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    property: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Property',
      required: true,
    },

    // Always derived on the server from the booking, never from the
    // request body — a client must not be able to choose what it owes.
    amount: {
      type: Number,
      required: true,
      min: [1, 'Payment amount must be positive.'],
    },

    currency: {
      type: String,
      default: 'INR',
    },

    provider: {
      type: String,
      enum: PAYMENT_PROVIDERS,
      default: 'demo',
    },

    paymentStatus: {
      type: String,
      enum: PAYMENT_RESULTS,
      default: 'pending',
    },

    // Generated by the server for demo payments; would come from the
    // gateway if a real provider were ever integrated.
    referenceId: {
      type: String,
      required: true,
      unique: true,
    },

    paymentDate: { type: Date, default: null },
    failureReason: { type: String, default: null },
  },
  { timestamps: true },
)

// One successful payment per booking. Partial index so repeated failed
// attempts are still allowed to exist alongside it.
paymentSchema.index(
  { booking: 1 },
  {
    unique: true,
    partialFilterExpression: { paymentStatus: 'success' },
    name: 'one_successful_payment_per_booking',
  },
)

export const Payment = mongoose.model('Payment', paymentSchema)
